import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Nav from "./components/Nav";
import Providers from "@/components/globalprovider/provider";

export const metadata: Metadata = {
  title: "Dacci",
  description: "Generated by Hammad",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Nav />
        <Toaster />
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}