import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Nav from "./components/Nav";
import Providers from "@/components/globalprovider/provider";
import { LoaderProvider } from "./context/LoaderContext";
import SmoothScroll from "./components/SmoothScroll";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Dacci",
  description: "Generated by Hammad",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <LoaderProvider>
          <Nav />
          <Toaster />
          <SmoothScroll>
            <Providers>
              {children}
            </Providers>
            <Footer />
          </SmoothScroll>
        </LoaderProvider>
      </body>
    </html>
  );
}